import os
import re
from pathlib import Path

BASE = Path(__file__).resolve().parent.parent  # "best you" vault dir
INDEX_FILE = BASE / "output" / "tree-index.md"
ROOT_DIR = BASE
# Obsidian alias syntax: [[target]] or [[target|alias]]. Capture target only.
WIKILINK_RE = re.compile(r"\[\[([^\]|]+)(?:\|[^\]]+)?\]\]")

def get_note_links(file_path):
    if not os.path.exists(file_path):
        return []
    with open(file_path, "r", encoding="utf-8") as f:
        return [m + ".md" for line in f for m in WIKILINK_RE.findall(line)]

def build_tree(root_files):
    tree = {}
    visited = set()

    def walk(file):
        if file in visited or not os.path.exists(file):
            return
        visited.add(file)
        links = get_note_links(file)
        tree[file] = [l for l in links if os.path.exists(l)]
        for link in tree[file]:
            walk(link)

    for root in root_files:
        walk(root)
    return tree

def print_tree(tree, current, level=0, visited=None):
    if visited is None:
        visited = set()  # single shared set -> diamonds print once
    lines = [f"{'  ' * level}- {current}"]
    if current in visited:
        return lines
    visited.add(current)
    for child in tree.get(current, []):
        lines.extend(print_tree(tree, child, level + 1, visited))
    return lines

def update_index():
    os.chdir(BASE)  # resolve note links relative to vault dir regardless of CWD
    roots = [
        "ROOT - best you - science of discipline.md",
        "ROOT - stworzenie kompletnego, systematycznego procesu budowy trwałej samodyscypliny i motywacji.md",
    ]
    tree = build_tree(roots)

    output = ["<!-- auto-generated by update_tree.py; do not edit -->", "# Knowledge Graph Tree", ""]
    for root in roots:
        output.extend(print_tree(tree, root))
        output.append("")

    INDEX_FILE.write_text("\n".join(output), encoding="utf-8")
    print(f"Tree updated -> {INDEX_FILE}")

if __name__ == "__main__":
    update_index()
